### ISSUE TITLE
部署出问题

### ISSUE THREAD

**Issue by Well-xu** [zjjlivein/Build-LLM-from-scratch#1]
Traceback (most recent call last):
  File "/home/xwh/Build-LLM-from-scratch/webui.py", line 11, in <module>
    from utils.callbacks import Iteratorize, Stream
ModuleNotFoundError: No module named 'utils'

**Comment by zjjlivein** [comment]
> Traceback (most recent call last): File "/home/xwh/Build-LLM-from-scratch/webui.py", line 11, in from utils.callbacks import Iteratorize, Stream ModuleNotFoundError: No module named 'utils'

增加了utils代码文件

**Comment by zjjlivein** [comment]
@Claude

**Comment by zjjlivein** [comment]
@claude code review
